In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn.metrics import mean_squared_error

In [2]:
# Load the Diabetes dataset
columns = 'age sex bmi map tc ldl hdl tch ltg glu'.split() # Declare the columns names
diabetes = datasets.load_diabetes() # Call the diabetes dataset from sklearn
df = pd.DataFrame(diabetes.data, columns=columns) # load the dataset as a pandas data frame
y1 = diabetes.target # define the target variable (dependent variable) as y
y=y1

# tasks 

In [20]:
#split datas randomly
arrx=df.age.head(50).index.to_numpy() 

split_n=3

row_n=len(arrx)
split_size_add=row_n%split_n
split_size=int((row_n-split_size_add)/split_n)

list_add=[]

list_add.append(np.random.choice(arrx, size=split_size_add, replace=False))


arrx[list_add]=-1

list_split=[]
arrx1=np.where(arrx > -1)
arrx1=np.asarray(arrx1).flatten()

for i in range (split_n):
    list1=(np.random.choice(arrx1, size=split_size, replace=False))
    
    for i in list1:
        arrx[i]=-1
        
    arrx1=arrx[arrx > -1]
       
    list_split.append(list1)


list_split[-1]=np.append(list_split[-1], list_add) 

list_split, list_add, list_split[0].shape




C:\Users\Lilit\anaconda3\lib\site-packages\ipykernel_launcher.py:15: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  from ipykernel import kernelapp as app


([array([43, 23,  2, 12, 22, 14, 35, 19, 44, 15, 49, 48, 34, 13,  8, 40],
        dtype=int64),
  array([26, 38, 46, 27, 11, 37,  7, 32, 36, 10, 20, 28,  6, 45,  3,  1],
        dtype=int64),
  array([25, 41, 21, 16, 33, 17, 29, 18, 31, 42, 39, 47,  5,  0, 24,  4,  9,
         30], dtype=int64)],
 [array([ 9, 30], dtype=int64)],
 (16,))

In [24]:
###test result by hand

list_slope=[]
list_inter=[]
list_x=[]
list_y=[]
x_index=[]
for split in range(1):  #change range first 1 then 2 then 3 and check result with test continue
    x_index=[]
    for i in range(len(list_split)):
        if (i!=split):
            x_index.extend(list_split[i])



    x=df.age[x_index].reset_index(drop=True)
    y=y1[x_index]


    x_mean=x.mean()
    y_mean=y.mean()

    Sxy=0
    Sxx=0

    for i in range(len(y)):
        Sxy += (x[i] - x_mean) * (y[i] - y_mean)
        Sxx += (x[i] - x_mean) ** 2
    

    slope=Sxy/Sxx
    intercept =y_mean-slope*x_mean
    
    list_slope.append(slope)
    list_inter.append(intercept)
list_y.extend(y)
list_x.extend(x)   
slope,intercept

(206.1942087857467, 148.6909931189266)

In [25]:
#test continue
#result by ordinary regression
arrx1=df.age.head(50).index.to_numpy()
x1=df.age[arrx1].reset_index(drop=True)
y1=y1[arrx1]

x=np.reshape(list_x,(-1,1))

y=list_y

reg = linear_model.LinearRegression()
model = reg.fit(x, y)
#compare with 
#model = reg.fit(x1.values.reshape(-1,1), y1)
#not the same result
#(array([151.49530745]), 143.9249229985232)
model.coef_, model.intercept_

(array([206.19420879]), 148.6909931189266)