In [3]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn.metrics import mean_squared_error

In [19]:
# Load the Diabetes dataset
columns = 'age sex bmi map tc ldl hdl tch ltg glu'.split() # Declare the columns names
diabetes = datasets.load_diabetes() # Call the diabetes dataset from sklearn
df = pd.DataFrame(diabetes.data, columns=columns) # load the dataset as a pandas data frame
y1 = diabetes.target # define the target variable (dependent variable) as y
y=y1
y2=y1

# tasks 

In [5]:
#split datas randomly
arrx=df.age.head(50).index.to_numpy() 

split_n=3

row_n=len(arrx)
split_size_add=row_n%split_n
split_size=int((row_n-split_size_add)/split_n)

list_add=[]

list_add.append(np.random.choice(arrx, size=split_size_add, replace=False))


arrx[list_add]=-1

list_split=[]
arrx1=np.where(arrx > -1)
arrx1=np.asarray(arrx1).flatten()

for i in range (split_n):
    list1=(np.random.choice(arrx1, size=split_size, replace=False))
    
    for i in list1:
        arrx[i]=-1
        
    arrx1=arrx[arrx > -1]
       
    list_split.append(list1)


list_split[-1]=np.append(list_split[-1], list_add) 

list_split, list_add, list_split[0].shape




C:\Users\Lilit\anaconda3\lib\site-packages\ipykernel_launcher.py:15: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  from ipykernel import kernelapp as app


([array([41,  7, 48, 46,  9, 13, 20, 28,  0, 45, 16, 29, 34, 27, 35, 19],
        dtype=int64),
  array([23, 14, 49,  8, 17, 24, 42,  6, 12, 37, 30, 32, 31, 38, 39,  5],
        dtype=int64),
  array([11, 40, 10, 15, 36, 22, 21, 33, 47, 26, 25,  4, 18,  1, 43,  2, 44,
          3], dtype=int64)],
 [array([44,  3], dtype=int64)],
 (16,))

In [8]:
###test result by hand

import statistics
list_slope=[]
list_inter=[]
list_x=[]
list_y=[]
x_index=[]
for split in range(3):  #change range first 1 then 2 then 3 and check result with test continue
    x_index=[]
    for i in range(len(list_split)):
        if (i!=split):
            x_index.extend(list_split[i])



    x=df.age[x_index].reset_index(drop=True)
    y=y1[x_index]


    x_mean=x.mean()
    y_mean=y.mean()

    Sxy=0
    Sxx=0

    for i in range(len(y)):
        Sxy += (x[i] - x_mean) * (y[i] - y_mean)
        Sxx += (x[i] - x_mean) ** 2
    

    slope=Sxy/Sxx
    intercept =y_mean-slope*x_mean
    
    list_slope.append(slope)
    list_inter.append(intercept)
    
slope=statistics.mean(list_slope)
intercept=statistics.mean(list_inter)

# list_y.extend(y)
# list_x.extend(x)   
slope,intercept

(156.25200673719485, 144.45200701738466)

In [24]:
#test continue
#result by ordinary regression
arrx1=df.age.head(50).index.to_numpy()
x1=df.age[arrx1].reset_index(drop=True)
y1=y1[arrx1]
x_test=df.age[50:100]
y_test=y2[50:100]

x=np.reshape(list_x,(-1,1))

y=list_y

reg = linear_model.LinearRegression()
model = reg.fit(x, y)
#compare with 
#model = reg.fit(x1.values.reshape(-1,1), y1)
#predictions = model.predict(x_test.values.reshape(-1,1))
#not the same result
#(array([151.49530745]), 143.9249229985232)
model.coef_, model.intercept_

(array([151.49530745]), 143.9249229985232)

In [25]:
pred_y=[]


pred_y=[intercept+slope*i for i in x_test]
    
pred_y

[149.83385238342302,
 153.80699234107578,
 136.21165824289918,
 143.0227553131611,
 136.779249665421,
 137.91443251046465,
 137.91443251046465,
 140.18479820055197,
 150.96903522846665,
 154.37458376359763,
 133.37370113029004,
 137.91443251046465,
 140.18479820055197,
 139.0496153555083,
 154.94217518611944,
 137.3468410879428,
 143.0227553131611,
 150.96903522846665,
 150.40144380594484,
 146.99589527081386,
 144.15793815820473,
 144.15793815820473,
 154.37458376359763,
 146.42830384829205,
 146.42830384829205,
 143.0227553131611,
 139.61720677803012,
 129.40056117263725,
 145.2931210032484,
 128.2653783275935,
 155.50976660864126,
 146.42830384829205,
 141.88757246811744,
 138.48202393298646,
 144.72552958072657,
 151.5366266509885,
 133.37370113029004,
 151.5366266509885,
 136.21165824289918,
 137.3468410879428,
 146.42830384829205,
 151.5366266509885,
 141.3199810455956,
 136.779249665421,
 132.23851828524639,
 133.37370113029004,
 153.23940091855397,
 140.18479820055197,
 144.725

In [29]:
from sklearn.model_selection import cross_val_score, cross_val_predict
x_index=df.age.head(50).index.to_numpy() 
x=df.age[x_index].reset_index(drop=True)
y=y1[x_index]

reg = linear_model.LinearRegression()
model = reg.fit(x.values.reshape(-1,1), y)
predic_cross = cross_val_predict(model, x.values.reshape(-1,1), y, cv=3)



In [31]:
rmse_hand=np.sqrt(mean_squared_error(y_test, pred_y))
rmse_reg=np.sqrt(mean_squared_error(y_test, predictions))
rmse_cross=np.sqrt(mean_squared_error(y_test, predic_cross))
rmse, rmse1, rmse_cross

(63.96607600525535, 63.8473783805944, 68.64760335390923)