#### 1. Import the numpy package under the name `np`

#### Import արեք numpy module-ը np անունով:

In [1]:
import numpy as np

#### 2. Create a numpy array of size 10 filled with zeros. 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array:

In [185]:
arr = np.zeros(10, dtype = np.int) 
print(arr)

[0 0 0 0 0 0 0 0 0 0]


#### 3.  How to get the documentation of the numpy add function? 

#### Նայեք numpy-ի add ֆունկցիայի դոկումենտացիան:

In [11]:
?np.add

#### 4.  Create a numpy array of size 10 filled with zeros but the fifth value is 1 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array, որի 5րդ արժեքը 1 է:

In [26]:
arr=(np.arange(10)==4)*1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 5.  Create a numpy array with values ranging from 10 to 49

#### Ստեղծեք 10-ից 49 հաջորդական թվերով numpy array:

In [31]:
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 6.  Reverse the numpy array ranging from 0 to 50. 

#### Ստեղծեք 0-ից 50 հաջորդական թվերով numpy array և տպեք այն շրջած ձևով:

In [33]:
arr=np.arange(0,50)
arr.reshape(50,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49]])

#### 7.  Create a 3x3 matrix with values ranging from 0 to 8 

#### Ստեղծեք 0-ից 8 հաջորդական թվերով 3x3 numpy array

In [36]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### Տրված է \[1,2,0,0,4,0\] numpy array-ը, գտեք ոչ-զրոյական արժեքներով տարրերի ինդեքսները:

In [39]:
arr=np.array([1,2,0,0,4,0])
arr[arr>0]

array([1, 2, 4])

#### 9. Create a 3x3x3 array with random integers from 1 to 20

#### Ստեղծեք 1-ից 20 պատահական թվերով լցված (3x3x3) չափանի numpy array:

In [69]:
arr=np.random.randint(1, 20, size=(3,3,3))
arr

array([[[10,  5, 11],
        [10, 10, 12],
        [12, 10, 15]],

       [[19,  3,  3],
        [16, 13,  1],
        [15, 11, 14]],

       [[10, 17,  4],
        [ 1,  6,  4],
        [10,  7,  5]]])

#### 10. Create a 10x10 array with random values and find the minimum and maximum values 

#### Ստեղծեք պատահական թվերով լցված (10x10) չափանի numpy array ու տպեք դրա փոքրագույն ու մեծագույն արժեքները:

In [106]:
arr=np.random.randint(1000,size=(10,10))

arr.min(),arr.max()

(9, 995)

#### 11. Create a random vector of size 30 and find the mean value 

#### Ստեղծեք 30 չափանի պատահական թվերով լցված numpy array ու տպեք դրա միջին արժեքը:

In [120]:
arr=np.random.randint(0,1000,30)
arr.mean()

472.1333333333333

#### 12. Given a 1D array ranging from 0 to 10, print all the elements which are between 3 and 8. 

#### Ստեղծեք 0-ից 10 հաջորդական թվերով numpy array: Տպեք բոլոր արժեքները, որոնք 3-ից 8 միջակայքում են:

In [139]:
arr=np.arange(0,11)
arr[(arr>3) & (arr<8)]


array([4, 5, 6, 7])

#### 13. Given a 1D array of 20 random integers from 0 to 10, multiply the values that are less than 5 by 2 and print the resulting array.

#### Ստեղծեք 1-ից 10 պատահական ամբողջ թվերով լցված 20 չափանի numpy array: Բազմապատկեք 5-ից փոքր արժեք ունեցող տարերրը 2-ով ու տպեք արդյունքում ստացված array-ը:

In [144]:
arr=np.random.randint(0,11,20)
arr, arr[arr<5]*2

(array([ 4,  5,  4,  4,  2,  6,  6, 10,  0,  3, 10,  0,  9, 10,  6,  8, 10,
        10,  7,  7]),
 array([8, 8, 8, 4, 0, 6, 0]))

#### 14. Given the 1D array [1, 5, 6, 2, -2, 23, 45], find the indices of the array elements that are divisible by 2.

#### Տրված է [1, 5, 6, 2, -2, 23, 45] numpy array-ը, գտեք 2-ի բաժանվող տարրերի կոորդինատները:

In [145]:
arr=np.array([1, 5, 6, 2, -2, 23, 45])
np.where(arr%2==0)

(array([2, 3, 4], dtype=int64),)

#### 15. Given a 1D array ranging from 0 to 20, print all the elements which are divisible by 3. 

#### Ստեղծեք 1-ից 20 հաջորդական թվերով լցված numpy array, տպեք բոլոր 3-ի բաժանվող տարրերի արժեքները:

In [151]:
arr=np.arange(1,21)
arr[arr%3==0]

array([ 3,  6,  9, 12, 15, 18])

#### 16. Create a 5x5 numpy array with each row values ranging from 0 to 4 

#### Ստեղծեք 5x5 numpy array, որի ամեն տող իրենից ներկայացնում է 0-ից 4 հաջորդական թվեր:

In [158]:
arr=np.arange(5)
np.tile(arr, (5,1))


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 17. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in the array.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի մեծագույն ու փոքրագույն արժեքները։

In [163]:
arr=np.array([[0, 1],[2, 3]])
arr.min(), arr.max()

(0, 3)

#### 18. Create the following 2x2 numpy array np.array([[0, 1],[2, 3]]). Find the minimum and maximum values in each column.

#### Ստեղծեք 2x2 numpy array np.array([[0, 1],[2, 3]]) : Գտեք array-ի սյուների մեծագույն ու փոքրագույն արժեքները։

In [170]:
arr=np.array([[0, 1],[2, 3]])
arr.min(0), arr.max(0)


(array([0, 1]), array([2, 3]))

#### 19. Create  numpy array of size 10 filled with integers of your choice. Compute mean, median, standard deviation and variance of the array values. 

#### Ստեղծեք 10 չափանի numpy array, հաշվեք array-ի mean, median, standard deviation և variance։

In [179]:
arr=np.random.randint(0,20,10)
#arr=np.array([1,2,3,4,5])
print(arr)
arr.mean(), np.median(arr), np.std(arr), np.var(arr)


[19 17 16 17  9  6 17 19 10 19]


(14.9, 17.0, 4.504442251822083, 20.290000000000003)

#### 20. Calculate the weighted average of the following array: np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5]) using weights np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]). 

#### Հաշվեք տրված array-ի կշռված միջինը՝ np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5])` օգտագործելով np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) weight-երը։

In [180]:
arr=np.array([2, 4, 3, 5, 6, 12, 34, 2, 34, 5])
wgt=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.average(arr,weights = wgt)

13.654545454545454

#### 21. Sort the rows of the following numpy array in an increasing order: np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]). 

#### Աճման կարգով դասավորեք տրված numpy array-ի տողերը՝ np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]]):

In [181]:
arr=np.array([[4, 2, 6, 1],[0, 2, 6, 1],[4, 4, 1, 9]])
np.sort(arr,1)

array([[1, 2, 4, 6],
       [0, 1, 2, 6],
       [1, 4, 4, 9]])

#### 22. Create the following numpy arrays and calculate the dot product between a and b. 

#### Ստեղծեք հետևյալ numpy array-ները ու հաշվեք a և b array-ների dot product-ը։

$$a = \begin{bmatrix} 3 & 6 & 7 \\ 5 & -3 & 0  \end{bmatrix}$$

$$b = \begin{bmatrix} 1 & 1 \\ 2 & 1 \\ 3 & -3 \end{bmatrix}$$

In [184]:
arr=np.array([[3,6,7],[5,-3,0]])
arr1=np.array([[1,1],[2,1],[3,-3]])
arr.dot(arr1)

array([[ 36, -12],
       [ -1,   2]])